[package]
name = "wring"
version = "0.1.0"
edition = "2021"
description = ""
license = "MIT"

[dependencies]
io-uring = "0.7.2"
libc = "0.2.80"

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }
tokio = { version = "1.42.0", features = ["full"] }
